apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluator
spec:
  selector:
    matchLabels:
      app: evaluator
  template:
    metadata:
      labels:
        app: evaluator
    spec:
      containers:
        - image: ghcr.io/hsiaofongw/expression-evaluator:0.0.1
          name: evaluator
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: evaluator
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: evaluator
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evaluator
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - evaluate.exploro.one
    secretName: evaluate-exploro-one-tls-secret
  rules:
  - host: evaluate.exploro.one
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: evaluator
            port:
              number: 80
